import badges from '../badges';

test('test badges function', async () => {
    let test_badge = [
        '<style type="text/css">',
        '.tooltip {position: relative; display: inline-block;}',
        '.tooltip .tooltiptext {visibility: hidden; width: 220px; background-color: #555; color: #fff; text-align: center;',
        '		border-radius: 6px; padding: 5px; padding-left: 3px; padding-right: 3px; position: absolute; z-index: 1; bottom: 200%; left: -30%;',
        '		margin-left: -100px; opacity: 0; transition: opacity 0.3s;}',
        '.tooltip .tooltiptext::after {content: ""; position: absolute; top: 100%; left: 85%; margin-left: -5px;', 
        '		border-width: 5px; border-style: solid; border-color: #555 transparent transparent transparent; }',
        '.tooltip:hover .tooltiptext {visibility: visible; opacity: 0.8;}',
        '	.badges{       ',
        '		width: 110px;',
        '   	height: 20px;',
        '		background-color: #3e3e3e;',
        '		border-radius: 3px;',   
        '		color: #fff;',
        '		text-align: center;',
        '		display: inline-block;',
        '		margin-right: 7px;',
        '		padding-left:2px',		
        '	}',
        '	#percent-activity{',
        '		width: 45px;',
        '		height: 20px;',
        '		float: right;',
        '		border-radius: 0 3px 3px 0;',
        '		text-align: center;',
        '		display: inline-block;',
        '		padding-left: 2px;',
        '	}',
        '	#percent-support{',
        '		width: 45px;',
        '		height: 20px;',
        '		float: right;',
        '		border-radius: 0 3px 3px 0;',
        '		text-align: center;',
        '		display: inline-block;',
        '		padding-left: 2px;',
        '	}',
        '#percent-welcoming{',
        '		width: 45px;',
        '		height: 20px;',
        '		float: right;',
        '		border-radius: 0 3px 3px 0;',
        '		text-align: center;',
        '		display: inline-block;',
        '		padding-left: 2px;',
        '	}',
        '	.text1{',
        '		font-size: 11px;',
        '		width: 59px;',
        '		padding-top: 2px;',
        '		font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;',
        '	}',
        '	.text2{',
        '		font-size: 11px;',
        '   	width: 40px;',
        '		padding-top: 2px;',
        '       height: 15px;',
        '		font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;',		
        '	}	',
        '</style>',
        '<div class="badges tooltip" id="my-badge">',
        '	<div id="percent-activity"><p class="text2"></p>',
        '	</div><p class="text1 "></p>',
        '	<span class="tooltiptext">Percentage calculated based on the number of commits, the number of contributors, event involving PRs, and active issues of the last month. Also, if release notes exist and are recent enough.</span>',
        '</div>',
        '<div class="badges tooltip" id="my-badge2">',
        '	<div id="percent-support"><p class="text2"></p>',
        '	</div><p class="text1"></p>',
        '	<span class="tooltiptext">Percentage calculated based on the checklist of the community profile, the number of contributors, events involving PRs and their features, and issues&apos; labels(&apos;Good-First-Issue&apos; and &apos;Help-Wanted&apos;) and feature.</span>',
        '</div>',
        '<div class="badges tooltip" id="my-badge3">',
        '	<div id="percent-welcoming"><p align="center" class="text2"></p>',
        '	</div><p class="text1"></p>',
        '	<span class="tooltiptext">Percentage calculated based on the checklist of the community profile, the existence of release note and if is recent enough as well and the number of active issues.</span>',
        '</div>',
    ].join('');
    expect(badges()).toBe(test_badge);
});
