import welcomingPage from '../welcomingPage'

test('test welcoming page', async () => {
    let TestWelcomingPage = [
        '<style>',
        '.full-element{',
        '   margin-left:30%;',
        '   margin-bottom:5%;',
        '}',
        '.block{',
        '   border-top:1px solid #d1d5da;',
        '}',
        '.left-element{',
        '   height:180px;',
        '   width: 50%;',
        '   border-right:1px solid #d1d5da;',
        '   display: inline-block;',
        '   margin: -1px -1px 0;',
        '   padding: 8px;',
        '}',
        '.right-element{',
        '   height:180px;',
        '   width: 50%;',
        '   display: inline-block;',
        '   margin: -1px -1px 0;',
        '   padding: 8px;',
        '}',
        '.left-element-top{',
        '   height:180px;',
        '   width: 50%;',
        '   border-right:1px solid #d1d5da;',
        '   display: inline-block;',
        '   margin: -1px -1px 0;',
        '   padding: 8px;',
        '}',
        '.right-element-top{',
        '   width: 50%;',
        '   display: inline-block;',
        '   margin: -1px -4px 0;',
        '   padding: 8px;',
        '   border-left: 1px solid #d1d5da;',
        '}',
        '</style>',
        '<div>',
        '   <div class="left-element-top">',
        '       <div id="different-contributors" style="margin-left:8%; margin-top:8%;"></div>',
        '   </div>',    
        '   <div class="right-element-top">',
        '       <div id="issue-activity" style="margin-left:8%;"></div>',
        '       <div id="issue-activity-rate" style="margin-left:8%; margin-top:8%;"></div>',
        '   </div>',
    
        '</div>',
        '<div class="block">',
        '   <div class="left-element">',
        '       <div id="help-wanted" style="margin-left:8%; margin-top:8%;"></div>',
        '   </div>',
        '   <div class="right-element">',
        '       <div id="good-first-issue" style="margin-left:8%; margin-top:8%;"></div>',
        '   </div>',
        '</div>',
        '<div class="block">',
        '   <div id="release-note" class="left-element"></div>',
        '   <div id="license" class="right-element"></div>',
        '</div>',
        '<div class="block">',
        '   <div id="readme" class="left-element"></div>',
        '   <div id="code-conduct" class="right-element"></div>',
        '</div>',
        '<div class="block">',
        '   <div id="issue-template" class="left-element"></div>',
        '   <div id="description" class="right-element"></div>',
        '</div>',
        '<div class="block" style="border-bottom: 1px solid #d1d5da;">',
        '   <div id="contribution-guide" class="left-element"></div>',
        '   <div id="pull-request-template" class="right-element"></div>',
        '</div>',
        '<div id="pull-request-graph" style="margin-top:3%;"></div>',
        '<div id="pull-request-quality" class="full-element"></div>',
    ].join('');
    expect(welcomingPage()).toBe(TestWelcomingPage);
});