version: '3'

services:
  hubcareplugin:
    container_name: hubcare-plugin
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/usr/src/app
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "35729:35729"