export default () => [
    '<style>',
    '.cx2{',
    '   height:360px;',
    '   width: 50%;',
    '   border-right:1px solid #d1d5da;',
    '   float: left;',
    '   margin: -1px -1px 0;',
    '   padding: 8px;',
    '   }',
    '.cx3{',
    '   height:150px;',
    '   width: 50%;',
    '   display: inline-block;',
    '   margin: -1px -1px 0;',
    '   padding: 8px;',
    '}',
    '.cx4{',
    '   height:209px;',
    '   width: 50%;',
    '   display: inline-block;',
    '   margin: -1px -1px 0;',
    '   padding: 8px;',
    '}',
    '.pr-bar-element{',
    '   margin-left:30%;',
    '   margin-bottom:5%;',
    '}',
    '.footer-element{',
    '   height: 200px;',
    '   padding-top: 30px;',
    '   padding-right: 30px;',
    '   padding-bottom: 50px;',
    '   padding-left: 80px;',
    '   border-top:1px solid #d1d5da;',
    '}',
    '</style>',
    '<div class="cx2"></div>',
    '<div class="cx3"></div>',
    '<div class="cx4"></div>',
    '<div id="pull-request-graph" style="margin-top:3%; margin-left:20%;"></div>',
    '<div id="pull-request-quality" class="pr-bar-element"></div>',
    '<div id="release-note" class="footer-element"></div>',
].join('');