// export default () => [
// '<style>',
// 
// '</style>',


// '<div style="width: 100px; height: 100px; display: inline; padding-right: 5px" id="my-badge" class="tooltip">',
// '<span class="tooltiptext">Percentage calculated based on the number of commits, the number of contributors, event involving PRs, and active issues of the last month. Also, if release notes exist and are recent enough.</span>',
// '</div>',

// '<div style="width: 100px; height: 100px; display: inline; padding-right: 5px" id="my-badge2" class="tooltip">',
// '<span class="tooltiptext">Percentage calculated based on the checklist of the community profile, the number of contributors, events involving PRs and their features, and issues` labels(´Good-First-Issue` and ´Help-Wanted`) and feature.</span>',
// '</div>',

// '<div style="width: 100px; height: 100px; display: inline; "id="my-badge3" class="tooltip">',
// '<span class="tooltiptext">Percentage calculated based on the checklist of the community profile, the existence of release note and if is recent enough as well and the number of active issues.</span>',
// '</div>'
// ].join('');

export default (colorPercent) => [
    '<style type="text/css">',
	'	.badges{       ',
	'		width: 110px;',
	'   	height: 20px;',
	'		background-color: #3e3e3e;',
	'		border-radius: 3px;',   
	'		color: #fff;',
	'		text-align: center;',
	'		display: inline-block;',
	'		margin-right: 7px;',
	'		padding-left:2px',		
	'	}',
	'	#percent-activity{',
	'		width: 45px;',
	'		height: 20px;',
	'		float: right;',
	'		border-radius: 0 3px 3px 0;',
	'		text-align: center;',
	'		display: inline-block;',
	'		padding-left: 2px;',
	'	}',
	'	#percent-support{',
	'		width: 45px;',
	'		height: 20px;',
	'		float: right;',
	'		border-radius: 0 3px 3px 0;',
	'		text-align: center;',
	'		display: inline-block;',
	'		padding-left: 2px;',
	'	}',
	'#percent-welcoming{',
	'		width: 45px;',
	'		height: 20px;',
	'		float: right;',
	'		border-radius: 0 3px 3px 0;',
	'		text-align: center;',
	'		display: inline-block;',
	'		padding-left: 2px;',
	'	}',
	'	.text1{',
	'		font-size: 11px;',
	'		width: 59px;',
	'		padding-top: 2px;',
	'		font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;',
	'	}',
	'	.text2{',
	'		font-size: 11px;',
	'   	width: 40px;',
	'		padding-top: 2px;',
	'       height: 15px;',
	'		font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;',		
	'	}	',
    '</style>',
	'<div class="badges" id="my-badge">',
	'<div id="percent-activity"><p class="text2"></p>',
    '</div><p class="text1"></p></div>',
    '<div class="badges" id="my-badge2"><div id="percent-support"><p class="text2"></p>',
    '</div><p class="text1"></p></div>',
    '<div class="badges" id="my-badge3"><div id="percent-welcoming"><p align="center" class="text2"></p>',
    '</div><p class="text1"></p></div>',
].join('');
