export default () => [
    '<div id="button" border: 1px solid transparent; ',
    'border-radius: 3px 3px 0 0; ',
    'border-top: 3px solid transparent; ',
    'color: #586069; ',
    'float: left; ',
    'padding: 7px 15px 8px; ',
    'white-space: nowrap; >',
    '<a id="hubcare-button" href="#hubcare" style=" ',
    'border: 1px solid transparent; ',
    'border-radius: 3px 3px 0 0; ',
    'border-top: 3px solid transparent; ',
    'color: #586069; ',
    'float: left; ',
    'padding: 7px 15px 8px; ',
    'text-decoration: none; ',
    'white-space: nowrap;  ',
    '  ">HubCare</a></div>',
].join('');