export default () => [
    '<style>',
    '.tooltip {position: relative; display: inline-block;}',
    '.tooltip .tooltiptext {visibility: hidden; width: 200px; background-color:rgb(41, 0, 102, 0.99);',
        'color: #fff; text-align: center; border-radius: 6px; padding: 5px 0; position:',
        'absolute; z-index: 1; bottom: 125%; left: 50%; margin-left: -60px; opacity: 0;',
        'transition: opacity 0.3s;}',
    '.tooltip .tooltiptext::after {position: absolute; -index: 1; bottom: 100%; left: 50%; margin-left: -60px;',
        'border-width: 5px; border-style: solid; border-color: #555 transparent transparent transparent;}',
    '.tooltip:hover .tooltiptext {visibility: visible; opacity: 1;}',
    '.badges{       ',
	'		width: 110px;',
	'   	height: 20px;',
	'		background-color: #3e3e3e;',
	'		border-radius: 3px;',   
	'		color: #fff;',
	'		text-align: center;',
	'		display: inline-block;',
	'		margin-right: 7px;',
	'		padding-left:2px',		
	'	}',
	'	#percent-activity{',
	'		width: 45px;',
	'		height: 20px;',
	'		float: right;',
	'		border-radius: 0 3px 3px 0;',
	'		text-align: center;',
	'		display: inline-block;',
	'		padding-left: 2px;',
	'	}',
	'	#percent-support{',
	'		width: 45px;',
	'		height: 20px;',
	'		float: right;',
	'		border-radius: 0 3px 3px 0;',
	'		text-align: center;',
	'		display: inline-block;',
	'		padding-left: 2px;',
	'	}',
	'#percent-welcoming{',
	'		width: 45px;',
	'		height: 20px;',
	'		float: right;',
	'		border-radius: 0 3px 3px 0;',
	'		text-align: center;',
	'		display: inline-block;',
	'		padding-left: 2px;',
	'	}',
	'	.text1{',
	'		font-size: 11px;',
	'		width: 59px;',
	'		padding-top: 3px;',
	'		font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;',
	'	}',
	'	.text2{',
	'		font-size: 11px;',
	'   	width: 40px;',
	'		padding-top: 3px;',
	'       height: 15px;',
	'		font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;',		
	'	}	',
    '</style>',

    '<div id="hubcare-page"',
        'style="margin-left: auto;margin-right: auto; width: 980px;',
        'background-color: #fff; border: 1px solid #d1d5da; border-radius: 3px;',
        'line-height: 1.25;">',
        '<div>',
            '<div style="text-align:center; width: 33%; padding-right: 5px;',
                'border: 1px solid #d1d5da; margin: -1px -1px 0; padding: 16px;',
                'border-bottom: 0px;" id="my-badge" class="tooltip" >',
                '<div class="badges" id="activity-badge">',
	            '   <div id="percent-activity"><p class="text2"></p>',
                '</div><p class="text1"></p></div>',
            '</div>',

            '<div style="text-align:center; width: 33%; padding-right: 5px;',
                'background-color: #f6f8fa; border: 1px solid #d1d5da;',
                'margin: -1px -1px 0; padding: 16px; 3px; border-bottom-left-radius: 5px;"',
                ' id="my-badge2" class="tooltip">',
                '<div class="badges" id="support-badge">',
                '   <div id="percent-support"><p class="text2"></p>',
                '   </div><p class="text1"></p></div>',
                '</div>',

            '<div style="text-align:center; width: 34.61%; padding-right: 5px;',
                'background-color: #f6f8fa; border: 1px solid #d1d5da;',
                'margin: -1px -1px 0; padding: 16px;" id="my-badge3" class="tooltip">',
                '<div class="badges" id="welcoming-badge">',
                '   <div id="percent-welcoming"><p align="center" class="text2"></p>',
                '</div><p class="text1"></p></div>',
            '</div>',
        '</div>',
        '<div id="hubcare-content">',
        '</div>',
    '</div>',
].join(''); 

