export default () => [
    '<div style="border: 8px solid rgba(0, 0, 0,.1); ',
    'margin: 0 auto; width: 50%; ',
    'border-left-color: #291E46; ',
    'justify-content: center; ',
    'align-items: center; ',
    'height: 60px; width: 60px; ',
    'border-radius: 50%; ',
    'animation: spin 1s linear infinite;" ',
    'id="loading"></div>',
    '<div style="text-align: center; margin: 2%; color: #24292e; ',
    'font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol; ',
    'font-size: 14px; line-height: 1.5;" id="text">',
    '   <p>You were the first person to review this repository today! ',
    '       We&apos;re doing the math for you. It will take less than a minute.</p>',
    '</div>',
].join('');
